

BEGIN EXECUTE IMMEDIATE 'DROP TABLE STORE_DATE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STORE_HOURS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STORE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CIRCUMSTANCE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE CIRCUMSTANCE (
    Location VARCHAR2(50) PRIMARY KEY,
    Fuel_Price NUMBER(5,2),
    Unemployment NUMBER(5,2),
    Temperature NUMBER(5,2)
);

CREATE TABLE STORE (
    StoreID VARCHAR2(5) PRIMARY KEY,
    Location VARCHAR2(50) REFERENCES CIRCUMSTANCE(Location)
);

CREATE TABLE EMPLOYEE (
    EmployeeID VARCHAR2(5) PRIMARY KEY,
    EmployeeName VARCHAR2(50),
    EmployeePosition VARCHAR2(30),
    StoreID VARCHAR2(5) REFERENCES STORE(StoreID)
);

CREATE TABLE STORE_HOURS (
    Day_ofWeek VARCHAR2(15) PRIMARY KEY,
    StoreID VARCHAR2(5) REFERENCES STORE(StoreID),
    Store_Hours VARCHAR2(20),
    Pharmacy_Hours VARCHAR2(20)
);

CREATE TABLE STORE_DATE (
    DateID VARCHAR2(5) PRIMARY KEY,
    SalesDate DATE,
    Day_ofWeek VARCHAR2(15) REFERENCES STORE_HOURS(Day_ofWeek),
    Weekly_Sales NUMBER(12,2),
    Holiday_Flag VARCHAR2(10),
    Holiday_Events VARCHAR2(30),
    CPI NUMBER(8,2)
);